#!/bin/bash

source "/data/SetupHelper/CommonResources"

configFile="/u-boot/config.txt"
modulesFile="/etc/modules"
pythonLibs="$scriptDir/ext"

packageLogFile="/var/log/dbus-i2c/current"

createFileIfNotExists ()
{
	if [ ! -f "$1" ]; then
		touch "$1"
		if [ ! -z "$2" ]; then
			chmod "$2" "$1"
		fi
	fi
}

insertLines ()
{
	if [ $(grep -c "$2" "$1") == 0 ]; then
		echo "#### Begin: dbus-i2c" >> "$1"
		echo "$2" >> "$1"
		echo "#### End: dbus-i2c" >> "$1"
		rebootNeeded="$3"
	fi
}

removeLines ()
{
	if [ -f "$1" ]; then
		if [ $(grep -c "#### Begin: dbus-i2c" "$1") != 0 ]; then
			sed -i -e '/#### Begin: dbus-i2c/,/#### End: dbus-i2c/d' "$1"
			rebootNeeded="$2"
		fi
	fi
}

extInstall ()
{
	branch=$3
	repoPath=$4
	if [ -z "$branch" ]; then
		branch="master"
	fi
	if [ -z "$repoPath" ]; then
		repoPath="$2"
	fi
	logMessage "++ Install Python library $2 ($branch) from $1 into $pythonLibs"
	wget "$1/archive/refs/heads/$branch.zip" -O "/tmp/$2.zip"
	mkdir -p "/tmp/$2"
	unzip -oq "/tmp/$2.zip" -d "/tmp/$2"
	if [ "$repoPath" == "/" ]; then
		# don't quote - need shell expansion!
		cp -R /tmp/$2/$2-$branch/* "$pythonLibs"
	else
		rm -fr "$pythonLibs/$2"
		mv "/tmp/$2/$2-$branch/$repoPath" "$pythonLibs/$2"
	fi
	rm -fr "/tmp/$2" "/tmp/$2.zip"
}

extUninstall ()
{
	logMessage "++ Removing Python libray $1"
	rm -fr "$pythonLibs/$1"
}

#### running manually and OK to proceed - prompt for input
if [ $scriptAction == 'NONE' ] ; then
	# display initial message
	echo
	echo "DBus support for I2C devices"
	
	standardActionPrompt
	createFileIfNotExists "$setupOptionsDir/bus-1"
	yesNoPrompt "Install BME280 service? [y/n]"
	if [ "$yesResponse" == 'true' ]; then
		createFileIfNotExists "$setupOptionsDir/device-bme280"
	fi
fi


#### install code goes here
if [ $scriptAction == 'INSTALL' ] ; then

	logMessage "++ Installing DBUS I2C services"

	insertLines "$configFile" "dtparam=i2c_arm=on" true
	createFileIfNotExists "$modulesFile"
	insertLines "$modulesFile" "i2c-dev" true
	mkdir -p "$pythonLibs"
	extInstall "https://github.com/victronenergy/velib_python" "velib_python" "master" "/"
	extInstall "https://github.com/kplindegaard/smbus2" "smbus2"

	if [ -f "$setupOptionsDir/device-bme280" ]; then
		extInstall "https://github.com/pulquero/bme280" "bme280"
	fi
fi


#### uninstalling - check scriptAction again
# if an install step failed package needs to be removed
if [ $scriptAction == 'UNINSTALL' ] ; then
	logMessage "++ Uninstalling DBUS I2C services"

	extUninstall "bme280"
	extUninstall "smbus2"
	removeLines "$configFile" true
	removeLines "$modulesFile" true
fi


endScript
